services:
  frontend:
    build:
      context: ./frontend/angular-app
      dockerfile: Dockerfile.frontend
    ports:
      - "4200:4200"
    networks:
      - app-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.backend
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/usr/src/app # Monta il codice sorgente
      - /usr/src/app/node_modules # Monta un volume anonimo per node_modules
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
