
%%{init: {'theme':'forest'}}%%

sequenceDiagram

    Title Sequence diagram of .ngOnInit() of /frontend/angular-app/src/app/visulizza-profilo/visulizza-profilo.component.ts

    participant p1 as ngOnInit()<br>:src/app/visulizza-profilo/visulizza-profilo.component.ts/visulizza-profilo.component.ts
    participant p2 as <br>:node_modules/%40angular/router/index.d.ts/index.d.ts
    participant p3 as <br>:node_modules/%40types/node/console.d.ts/console.d.ts
    participant p4 as <br>:node_modules/rxjs/dist/types/internal/Observable.d.ts/Observable.d.ts
    participant p5 as <br>:src/app/_services/rest-api.service.ts/rest-api.service.ts
    participant p6 as <br>:src/app/_services/auth.service.ts/auth.service.ts
    participant p7 as <br>:node_modules/%40angular/common/http/index.d.ts/index.d.ts


	p1 ->>+ p2: 1: get('nickname')
	p2 -->>- p1: 1: return value
	p1 ->>+ p2: 2: get('nickname')
	p2 -->>- p1: 2: return value
	p1 ->>+ p2: 3: paramMap.
	p2 -->>- p1: 3: return value
	p1 ->>+ p2: 4: paramMap.
	p2 -->>- p1: 4: return value
	p1 ->>+ p3: 5: log('il nickname', this.nickname)
	p3 -->>- p1: 5: return value
	p1 ->>+ p3: 6: log('il nickname', this.nickname)
	p3 -->>- p1: 6: return value
	p1 ->>+ p3: 7: log('Utente trovato:', this.utente)
	p3 -->>- p1: 7: return value
	p1 ->>+ p3: 8: log('Utente trovato:', this.utente)
	p3 -->>- p1: 8: return value
	p1 ->>+ p4: 9: subscribe({ next: (data) => { this.<br>.utente = data; // Memorizza i dati<br>dell'utente          console.log(<br>('Utente trovato:', this.utente);<br>},        error: (err) =><br>{          console.error('Errore<br>nel recupero dell 'utente:', err)<br>);          this.errorMessage =<br>'Errore nel recupero delle informazioni<br>dell 'utente';        },<br>})
	p4 -->>- p1: 9: return value
	p1 ->>+ p4: 10: subscribe({ next: (data) => { this.<br>.utente = data; // Memorizza i dati<br>dell'utente          console.log(<br>('Utente trovato:', this.utente);<br>},        error: (err) =><br>{          console.error('Errore<br>nel recupero dell 'utente:', err)<br>);          this.errorMessage =<br>'Errore nel recupero delle informazioni<br>dell 'utente';        },<br>})
	p4 -->>- p1: 10: return value
	p1 ->>+ p5: 11: getUtenteByNickname(this.nickname)
	p5 ->>+ p6: 11.1: getToken()
	p6 -->>- p5: 11.1: return value
	p5 ->>+ p6: 11.2: getToken()
	p6 -->>- p5: 11.2: return value
	p5 ->>+ p7: 11.3: get<
	p7 -->>- p5: 11.3: return value
	p5 ->>+ p7: 11.4: get<
	p7 -->>- p5: 11.4: return value
	p5 -->>- p1: 11: return value
	p1 ->>+ p5: 12: getUtenteByNickname(this.nickname)
	p5 ->>+ p6: 12.1: getToken()
	p6 -->>- p5: 12.1: return value
	p5 ->>+ p6: 12.2: getToken()
	p6 -->>- p5: 12.2: return value
	p5 ->>+ p7: 12.3: get<
	p7 -->>- p5: 12.3: return value
	p5 ->>+ p7: 12.4: get<
	p7 -->>- p5: 12.4: return value
	p5 -->>- p1: 12: return value
	p1 ->>+ p5: 13: getUtenteByNickname(this.nickname)
	p5 ->>+ p6: 13.1: getToken()
	p6 -->>- p5: 13.1: return value
	p5 ->>+ p6: 13.2: getToken()
	p6 -->>- p5: 13.2: return value
	p5 ->>+ p7: 13.3: get<
	p7 -->>- p5: 13.3: return value
	p5 ->>+ p7: 13.4: get<
	p7 -->>- p5: 13.4: return value
	p5 -->>- p1: 13: return value
	p1 ->>+ p5: 14: getUtenteByNickname(this.nickname)
	p5 ->>+ p6: 14.1: getToken()
	p6 -->>- p5: 14.1: return value
	p5 ->>+ p6: 14.2: getToken()
	p6 -->>- p5: 14.2: return value
	p5 ->>+ p7: 14.3: get<
	p7 -->>- p5: 14.3: return value
	p5 ->>+ p7: 14.4: get<
	p7 -->>- p5: 14.4: return value
	p5 -->>- p1: 14: return value
	p1 ->>+ p3: 15: error('Errore nel recupero dell<br>'utente:', err)
	p3 -->>- p1: 15: return value
	p1 ->>+ p3: 16: error('Errore nel recupero dell<br>'utente:', err)
	p3 -->>- p1: 16: return value
        