FROM node:18

# Crea una directory di lavoro
WORKDIR /usr/src/app

# Installa i pacchetti necessari
RUN apt-get update && apt-get install -y \
    build-essential \
    sqlite3 \
    libsqlite3-dev

# Copia i file di configurazione per installare le dipendenze
COPY package*.json ./

# Installa le dipendenze
RUN npm install --build-from-source --unsafe-perm

# Copia il resto del codice sorgente
COPY . .

# porta
EXPOSE 3000

# Comando di avvio
CMD ["node", "server.js"]
